exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([{
          "firstname": "",
          "lastname": "",
          "username": "nigel",
          "email": "nigel@email.com",
          "password": "password",
          "phonenumber": "9876543210",
          "role": "user",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577193017849-user-avatar.png",
          "created_at": "2019-12-16 10:19:46",
          "updated_at": "2019-12-16 10:19:46"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "nakaz",
          "email": "nakaz@email.com",
          "password": "password1",
          "phonenumber": "1234567890",
          "role": "",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577192944119-manager-avatar.jpg",
          "created_at": "2019-12-16 10:19:46",
          "updated_at": "2019-12-16 10:19:46"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "jaywon",
          "email": "jaywon@email.com",
          "password": "password12",
          "phonenumber": "9949393483",
          "role": "user",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577193020426-user-avatar.png",
          "created_at": "2019-12-16 10:19:46",
          "updated_at": "2019-12-16 10:19:46"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "smith",
          "email": "smith@email.com",
          "password": "password123",
          "phonenumber": "8332005225",
          "role": "",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577192999213-manager-avatar.jpg",
          "created_at": "2019-12-17 18:03:14",
          "updated_at": "2019-12-17 18:03:14"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "john",
          "email": "john@email.com",
          "password": "password1234",
          "phonenumber": "7661876696",
          "role": "user",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577193023447-user-avatar.png",
          "created_at": "2019-12-17 18:19:50",
          "updated_at": "2019-12-17 18:19:50"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "admin",
          "email": "admin@email.com",
          "password": "1234",
          "phonenumber": "8886197968",
          "role": "admin",
          "assigned_roles": "user",
          "designation": "Mean stack developer",
          "department": "IT\/Software",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577185274805-admin-avatar.png",
          "created_at": "2019-12-19 10:27:00",
          "updated_at": "2019-12-19 10:27:00"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "user",
          "email": "user@email.com",
          "password": "1234",
          "phonenumber": "1234567890",
          "role": "user",
          "assigned_roles": "user",
          "designation": "Graphics designer",
          "department": "IT\/Application Software",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577185233446-user-avatar.png",
          "created_at": "2019-12-19 10:29:07",
          "updated_at": "2019-12-19 10:29:07"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "manager",
          "email": "manager@email.com",
          "password": "1234",
          "phonenumber": "9876543210",
          "role": "",
          "assigned_roles": "user",
          "designation": "Project manager",
          "department": "IT\/Application Programmer",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577185256048-manager-avatar.jpg",
          "created_at": "2019-12-19 10:29:33",
          "updated_at": "2019-12-19 10:29:33"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "test",
          "email": "test@email.com",
          "password": "1234",
          "phonenumber": "9848022338",
          "role": "user",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577193029585-user-avatar.png",
          "created_at": "2019-12-19 11:48:09",
          "updated_at": "2019-12-19 11:48:09"
        },
        {
          "firstname": "",
          "lastname": "",
          "username": "sample",
          "email": "sample@email.com",
          "password": "1234",
          "phonenumber": "9704078341",
          "role": "",
          "assigned_roles": "user",
          "designation": "",
          "department": "",
          "profilePath": "D:\\node\\NodePro\\public\\profiles\\file-1577193032305-user-avatar.png",
          "created_at": "2019-12-19 11:49:46",
          "updated_at": "2019-12-19 11:49:46"
        }
      ]);
    });
};